[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x66c085f290850926bd20723d2e36b42e770534ceeda007b843a65c880c145ef"
transaction_hash = "0x34d7f94a9172a22ca49ba40d40b3803f31194b0c41bf41c519c8087cbee09df"
block_number = 3
seed = "taleweaver"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/taleweaver/katana"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x8cd11b7653ac1f815aa1e47f664bd37f8790802f74da17b71206a75219c54c"
class_hash = "0x1e5c84cd08a31992b4320c3b39684df42d4fa292a09f382f89fd5f639b2c03e"
original_class_hash = "0x1e5c84cd08a31992b4320c3b39684df42d4fa292a09f382f89fd5f639b2c03e"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/taleweaver_systems_construct_construct.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "taleweaver::systems::construct::construct"

[[contracts]]
kind = "DojoContract"
address = "0x64887a09aec35c5eb705d95dc075967fd42bcb4b51c2104da4ccb4dbeb56b5c"
class_hash = "0x468c374475816853142224935ce0e76f812ea8164010b3a2c0187a68b20015e"
original_class_hash = "0x468c374475816853142224935ce0e76f812ea8164010b3a2c0187a68b20015e"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/taleweaver_systems_decision_decision.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "taleweaver::systems::decision::decision"

[[contracts]]
kind = "DojoContract"
address = "0x2b3e356d28bb92f2f018c538d6bb0622ccbc4813e9968d80f16355a39a4d717"
class_hash = "0x2bb82d201cb3f90ef470405a7ebfaf9098723de7fbd87b64c4b7dfbd6dbb1aa"
original_class_hash = "0x2bb82d201cb3f90ef470405a7ebfaf9098723de7fbd87b64c4b7dfbd6dbb1aa"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/taleweaver_systems_play_play.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "taleweaver::systems::play::play"

[[contracts]]
kind = "DojoContract"
address = "0x3f1e7204d3d202f38d3737edc2233237c7a11fc17c6771f6c433a0138699bcf"
class_hash = "0x7cc334d09f7f8396a53f36201bd7d5284b1136aa032c7124d5770576b9e04f4"
original_class_hash = "0x7cc334d09f7f8396a53f36201bd7d5284b1136aa032c7124d5770576b9e04f4"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/taleweaver_systems_score_score.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "taleweaver::systems::score::score"

[[models]]
kind = "DojoModel"
class_hash = "0x3a94c67edc510c6e7068ba035b7dcd83754a18b77c423b19204e9ee7acb772d"
original_class_hash = "0x3a94c67edc510c6e7068ba035b7dcd83754a18b77c423b19204e9ee7acb772d"
abi = "manifests/dev/abis/deployments/models/taleweaver_models_decision_decision.json"
name = "taleweaver::models::decision::decision"

[[models.members]]
name = "assistantId"
type = "felt252"
key = true

[[models.members]]
name = "threadId"
type = "felt252"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "runId"
type = "felt252"
key = false

[[models.members]]
name = "cidA"
type = "felt252"
key = false

[[models.members]]
name = "cidB"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6c3b23fc0e59543a78753f4faa5b6d91f80a5052c47664f869ab8b82e45bdcf"
original_class_hash = "0x6c3b23fc0e59543a78753f4faa5b6d91f80a5052c47664f869ab8b82e45bdcf"
abi = "manifests/dev/abis/deployments/models/taleweaver_models_score_score.json"
name = "taleweaver::models::score::score"

[[models.members]]
name = "assistantId"
type = "felt252"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "points"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x763a1d457b0a62f14b3747639fd4a6f7061bca16df4171958736d3aaa4435b9"
original_class_hash = "0x763a1d457b0a62f14b3747639fd4a6f7061bca16df4171958736d3aaa4435b9"
abi = "manifests/dev/abis/deployments/models/taleweaver_models_seed_seed.json"
name = "taleweaver::models::seed::seed"

[[models.members]]
name = "assistantId"
type = "felt252"
key = true

[[models.members]]
name = "creator"
type = "ContractAddress"
key = false

[[models.members]]
name = "cidA"
type = "felt252"
key = false

[[models.members]]
name = "cidB"
type = "felt252"
key = false
