kind = "DojoModel"
class_hash = "0x763a1d457b0a62f14b3747639fd4a6f7061bca16df4171958736d3aaa4435b9"
original_class_hash = "0x763a1d457b0a62f14b3747639fd4a6f7061bca16df4171958736d3aaa4435b9"
abi = "manifests/dev/abis/base/models/taleweaver_models_seed_seed.json"
name = "taleweaver::models::seed::seed"

[[members]]
name = "assistantId"
type = "felt252"
key = true

[[members]]
name = "creator"
type = "ContractAddress"
key = false

[[members]]
name = "cidA"
type = "felt252"
key = false

[[members]]
name = "cidB"
type = "felt252"
key = false
