kind = "DojoModel"
class_hash = "0x3a94c67edc510c6e7068ba035b7dcd83754a18b77c423b19204e9ee7acb772d"
original_class_hash = "0x3a94c67edc510c6e7068ba035b7dcd83754a18b77c423b19204e9ee7acb772d"
abi = "manifests/dev/abis/base/models/taleweaver_models_decision_decision.json"
name = "taleweaver::models::decision::decision"

[[members]]
name = "assistantId"
type = "felt252"
key = true

[[members]]
name = "threadId"
type = "felt252"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "runId"
type = "felt252"
key = false

[[members]]
name = "cidA"
type = "felt252"
key = false

[[members]]
name = "cidB"
type = "felt252"
key = false
