kind = "DojoContract"
class_hash = "0x7cc334d09f7f8396a53f36201bd7d5284b1136aa032c7124d5770576b9e04f4"
original_class_hash = "0x7cc334d09f7f8396a53f36201bd7d5284b1136aa032c7124d5770576b9e04f4"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/taleweaver_systems_score_score.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "taleweaver::systems::score::score"
